# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'ssh://git@bitbucket.iunetworks.am:7999/ipods/iupodspecs.git'

target 'DCTask' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'RxSwift', '~> 5'

end
